capture_type: esp32 # webcam or esp32
frames_per_second: 20
laser_tracking_type: gaussian # gaussian or hsv
landmine_tracking_type: hsv # gaussian or hsv
esp32_server:
  scheme: http
  host: 10.0.0.199
  image_endpoint: capture
  control_endpoint: control
frame_stack: horizontal # horizontal or vertical